// vant工具
import Vue from 'vue'
import { Checkbox, Button, Switch, Rate, Tabbar, TabbarItem, NavBar, Form, Field, Toast, Icon, Swipe, SwipeItem, Lazyload, Search, Grid, GridItem, DropdownMenu, DropdownItem, Sidebar, SidebarItem, SubmitBar, GoodsAction, GoodsActionIcon, GoodsActionButton, ActionSheet, Stepper, Dialog, RadioGroup, Radio, Tab, Tabs, Pagination, AddressList, AddressEdit, Area } from 'vant'

Vue.use(Area)
Vue.use(AddressEdit)
Vue.use(AddressList)
Vue.use(Pagination)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Field)
Vue.use(Radio)
Vue.use(RadioGroup)
// 全局注册
Vue.use(Checkbox)
Vue.use(Dialog)
Vue.use(Stepper)
Vue.use(ActionSheet)
Vue.use(GoodsAction)
Vue.use(GoodsActionButton)
Vue.use(GoodsActionIcon)
Vue.use(SubmitBar)
Vue.use(Sidebar)
Vue.use(SidebarItem)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Search)
Vue.use(Lazyload)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Icon)
Vue.use(Toast)
Vue.use(Form)
Vue.use(Field)
Vue.use(NavBar)
Vue.use(Tabbar)
Vue.use(TabbarItem)

Vue.use(Button)
Vue.use(Switch)
Vue.use(Rate)
